In [2]:
import numpy as np
import scipy

In [5]:
n = 3

random_matrix = np.random.random([n, n])
print(random_matrix)

matrix_inv = np.linalg.inv(random_matrix)
print(matrix_inv)

check_product = np.linalg.matmul(random_matrix, matrix_inv)
print(check_product)

[[0.1653963  0.69327368 0.45887125]
 [0.59313222 0.04368153 0.8043763 ]
 [0.25327223 0.19572358 0.14817682]]
[[-1.45812335 -0.12474531  5.19266825]
 [ 1.11885634 -0.88582478  1.34383673]
 [ 1.01443389  1.38328869 -3.90195447]]
[[ 1.00000000e+00 -5.12321260e-17  9.74453843e-17]
 [ 1.00594003e-16  1.00000000e+00 -1.01985022e-16]
 [-9.23022760e-18 -3.89822904e-17  1.00000000e+00]]


In [8]:
n = 3

vector_a = np.random.random(n)
vector_b = np.random.random(n)

print(vector_a)
print(vector_b)

dot_product = np.dot(vector_a, vector_b)
print(dot_product)

[0.08977134 0.94037403 0.25793161]
[0.63366779 0.57294351 0.07513906]
0.615047144747685


In [3]:
n = 3
m = 3

A = np.random.random([m, n])
x = np.random.random(n)

print(A)
print(x)

Ax = np.linalg.matmul(A, x)
print(Ax)

[[0.26170095 0.52333654 0.62754413]
 [0.57371362 0.67941737 0.88743121]
 [0.47717523 0.33027759 0.87130543]]
[0.13300763 0.43954986 0.09221414]
[0.32270917 0.4567798  0.28898809]


In [4]:
n = 3

A = np.random.random((3,3))
b = np.random.random(3)

print(A)
print(b)

x = scipy.linalg.solve(A, b)
print(x)

[[0.5423115  0.02308936 0.10496859]
 [0.07410878 0.44717877 0.99677874]
 [0.68701546 0.87894118 0.41348969]]
[0.55935294 0.61887345 0.63946559]
[ 0.9106384  -0.30988526  0.69219099]


In [6]:
n = 3

A = np.random.random((3,3))
print(A)

eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[[0.57646626 0.49202229 0.89242923]
 [0.07455351 0.23385747 0.43068511]
 [0.71924372 0.97505223 0.14470232]]
[ 1.45952232  0.16456774 -0.66906401]
[[-0.75411524 -0.80355707 -0.44802757]
 [-0.25807756  0.59362912 -0.35449024]
 [-0.60390909  0.04359472  0.82073623]]
